version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "bun"
    assignees:
      - "vexxvakan"
    reviewers:
      - "vexxvakan"
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "@biomejs/biome"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "typescript"
          - "@biomejs/biome"
        update-types:
          - "patch"
    # Auto-merge rules
    allow:
      - dependency-type: "development"
      - dependency-type: "production"
    ignore:
      # Ignore major updates for critical dependencies
      - dependency-name: "@modelcontextprotocol/sdk"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "03:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "github-actions"
    assignees:
      - "vexxvakan"
    pull-request-branch-name:
      separator: "-"
