name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean

jobs:
  test:
    name: Test Suite
    uses: ./.github/workflows/jobs/test.yml
    secrets: inherit
    with:
      debug_enabled: ${{ inputs.debug_enabled || false }}

  build:
    name: Build
    needs: test
    uses: ./.github/workflows/jobs/build.yml
    secrets: inherit

  code-quality:
    name: Quality
    needs: test
    uses: ./.github/workflows/jobs/code-quality.yml
    secrets: inherit

  integration-test:
    name: Integration
    needs: build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/jobs/integration-test.yml
    secrets: inherit

  status-check:
    name: CI Status Check
    runs-on: ubuntu-latest
    needs: [test, build, code-quality]
    if: always()

    steps:
      - name: Check CI Status
        run: |
          if [ "${{ needs.test.result }}" != "success" ] || \
             [ "${{ needs.build.result }}" != "success" ] || \
             [ "${{ needs.code-quality.result }}" != "success" ]; then
            echo "❌ CI pipeline failed"
            echo "Test: ${{ needs.test.result }}"
            echo "Build: ${{ needs.build.result }}"
            echo "Quality: ${{ needs.code-quality.result }}"
            exit 1
          fi
          echo "✅ CI pipeline passed successfully!"

      - name: Create status summary
        if: always()
        run: |
          echo "## CI Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Test Suite | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ${{ needs.build.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Quality | ${{ needs.code-quality.result }} |" >> $GITHUB_STEP_SUMMARY